"""empty message

Revision ID: 0b5b9e7ac2d1
Revises: 557ef48a1e0c
Create Date: 2019-03-18 14:25:44.602181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5b9e7ac2d1'
down_revision = '557ef48a1e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
