"""empty message

Revision ID: aa30d28fc366
Revises: 
Create Date: 2019-01-25 09:13:21.123519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa30d28fc366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_img', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('cover_img', sa.String(length=255), nullable=False),
    sa.Column('lecturer', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gratitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gratitude_from_id'), 'gratitude', ['from_id'], unique=False)
    op.create_index(op.f('ix_gratitude_to_id'), 'gratitude', ['to_id'], unique=False)
    op.create_table('news_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cls_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('img_src', sa.String(length=255), nullable=False),
    sa.Column('brief', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('is_banner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cls_id'], ['news_class.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_cls_id'), 'news', ['cls_id'], unique=False)
    op.create_table('HD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HD_admin_id'), 'HD', ['admin_id'], unique=False)
    op.create_table('dealer_gain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['admin.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['dealer_training.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_gain_dealer_id'), 'dealer_gain', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_gain_training_id'), 'dealer_gain', ['training_id'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('dealer_training_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealer_training_id'], ['dealer_training.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_admin_id'), 'experience', ['admin_id'], unique=False)
    op.create_index(op.f('ix_experience_dealer_training_id'), 'experience', ['dealer_training_id'], unique=False)
    op.create_table('gratitude_star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('year_month', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gratitude_star_staff_id'), 'gratitude_star', ['staff_id'], unique=False)
    op.create_table('hd__ans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ans', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('hd_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hd_id'], ['HD.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hd__ans_admin_id'), 'hd__ans', ['admin_id'], unique=False)
    op.create_index(op.f('ix_hd__ans_hd_id'), 'hd__ans', ['hd_id'], unique=False)
    op.create_table('newtest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(length=125), nullable=False),
    sa.Column('select', sa.String(length=255), nullable=True),
    sa.Column('blanks', sa.String(length=255), nullable=True),
    sa.Column('shortAns', sa.String(length=255), nullable=True),
    sa.Column('picQues', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newtest_staff_id'), 'newtest', ['staff_id'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('creaet_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_staff_id'), 'points', ['staff_id'], unique=False)
    op.create_table('lesson_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_collection_lesson_id'), 'lesson_collection', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_collection_staff_id'), 'lesson_collection', ['staff_id'], unique=False)
    op.create_table('lesson_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_comment_lsn_id'), 'lesson_comment', ['lsn_id'], unique=False)
    op.create_index(op.f('ix_lesson_comment_staff_id'), 'lesson_comment', ['staff_id'], unique=False)
    op.create_table('lesson_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('bu_id', sa.Integer(), nullable=False),
    sa.Column('need_manager', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bu_id'], ['business_unit.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_permission_bu_id'), 'lesson_permission', ['bu_id'], unique=False)
    op.create_index(op.f('ix_lesson_permission_lsn_id'), 'lesson_permission', ['lsn_id'], unique=False)
    op.create_table('lesson_thumb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_thumb_lsn_id'), 'lesson_thumb', ['lsn_id'], unique=False)
    op.create_index(op.f('ix_lesson_thumb_staff_id'), 'lesson_thumb', ['staff_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.Text(), nullable=False),
    sa.Column('other_option', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_lsn_id'), 'question', ['lsn_id'], unique=False)
    op.create_table('testing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testing_lsn_id'), 'testing', ['lsn_id'], unique=False)
    op.create_index(op.f('ix_testing_staff_id'), 'testing', ['staff_id'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_lsn_id'), 'tool', ['lsn_id'], unique=False)
    op.create_table('training_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('lsn_id', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('finish_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lsn_id'], ['lesson.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_task_lsn_id'), 'training_task', ['lsn_id'], unique=False)
    op.create_index(op.f('ix_training_task_staff_id'), 'training_task', ['staff_id'], unique=False)
    op.create_table('tool_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_collection_staff_id'), 'tool_collection', ['staff_id'], unique=False)
    op.create_index(op.f('ix_tool_collection_tool_id'), 'tool_collection', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_collection_tool_id'), table_name='tool_collection')
    op.drop_index(op.f('ix_tool_collection_staff_id'), table_name='tool_collection')
    op.drop_table('tool_collection')
    op.drop_index(op.f('ix_training_task_staff_id'), table_name='training_task')
    op.drop_index(op.f('ix_training_task_lsn_id'), table_name='training_task')
    op.drop_table('training_task')
    op.drop_index(op.f('ix_tool_lsn_id'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_testing_staff_id'), table_name='testing')
    op.drop_index(op.f('ix_testing_lsn_id'), table_name='testing')
    op.drop_table('testing')
    op.drop_index(op.f('ix_question_lsn_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_lesson_thumb_staff_id'), table_name='lesson_thumb')
    op.drop_index(op.f('ix_lesson_thumb_lsn_id'), table_name='lesson_thumb')
    op.drop_table('lesson_thumb')
    op.drop_index(op.f('ix_lesson_permission_lsn_id'), table_name='lesson_permission')
    op.drop_index(op.f('ix_lesson_permission_bu_id'), table_name='lesson_permission')
    op.drop_table('lesson_permission')
    op.drop_index(op.f('ix_lesson_comment_staff_id'), table_name='lesson_comment')
    op.drop_index(op.f('ix_lesson_comment_lsn_id'), table_name='lesson_comment')
    op.drop_table('lesson_comment')
    op.drop_index(op.f('ix_lesson_collection_staff_id'), table_name='lesson_collection')
    op.drop_index(op.f('ix_lesson_collection_lesson_id'), table_name='lesson_collection')
    op.drop_table('lesson_collection')
    op.drop_index(op.f('ix_points_staff_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_newtest_staff_id'), table_name='newtest')
    op.drop_table('newtest')
    op.drop_index(op.f('ix_hd__ans_hd_id'), table_name='hd__ans')
    op.drop_index(op.f('ix_hd__ans_admin_id'), table_name='hd__ans')
    op.drop_table('hd__ans')
    op.drop_index(op.f('ix_gratitude_star_staff_id'), table_name='gratitude_star')
    op.drop_table('gratitude_star')
    op.drop_index(op.f('ix_experience_dealer_training_id'), table_name='experience')
    op.drop_index(op.f('ix_experience_admin_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_dealer_gain_training_id'), table_name='dealer_gain')
    op.drop_index(op.f('ix_dealer_gain_dealer_id'), table_name='dealer_gain')
    op.drop_table('dealer_gain')
    op.drop_index(op.f('ix_HD_admin_id'), table_name='HD')
    op.drop_table('HD')
    op.drop_index(op.f('ix_news_cls_id'), table_name='news')
    op.drop_table('news')
    op.drop_table('user_resources')
    op.drop_table('teacher')
    op.drop_table('resources')
    op.drop_table('news_class')
    op.drop_index(op.f('ix_gratitude_to_id'), table_name='gratitude')
    op.drop_index(op.f('ix_gratitude_from_id'), table_name='gratitude')
    op.drop_table('gratitude')
    op.drop_table('faq')
    op.drop_table('dealer_training')
    op.drop_table('a_banner')
    # ### end Alembic commands ###
