"""empty message

Revision ID: e3c45106b25d
Revises: 0b5b9e7ac2d1
Create Date: 2019-03-20 09:54:46.272466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c45106b25d'
down_revision = '0b5b9e7ac2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('sumprice', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'sumprice')
    # ### end Alembic commands ###
