"""empty message

Revision ID: fbc13f4d9c96
Revises: fc36a41d4c3e
Create Date: 2019-03-20 15:52:12.031061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbc13f4d9c96'
down_revision = 'fc36a41d4c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'fullmarks',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'lesson_',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'lesson_dayno',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'newnumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'newnumber_day',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'passed',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'passed_dayno',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'resnumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'resnumber_day',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'toolnumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'toolnumber_day',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'toolnumber_day',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'toolnumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'resnumber_day',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'resnumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'passed_dayno',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'passed',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'newnumber_day',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'newnumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'lesson_dayno',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'lesson_',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'fullmarks',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
